/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package administrarAgenda;

import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author JHumaran
 */
public class ImprimirCitas extends javax.swing.JFrame {
    PanelTransparente panelTransparente = new PanelTransparente();
    int checkBoxSabado = 0;
    int checkBoxDomingo = 0;
    ImageIcon checkBox = new ImageIcon("C:\\Users\\JHumaran\\Documents\\GitHub\\SAREI\\SAREI.Presentacion\\src\\administrarAgenda\\img/checkedBox.png"); 
    ImageIcon uncheckedBox = new ImageIcon("C:\\Users\\JHumaran\\Documents\\GitHub\\SAREI\\SAREI.Presentacion\\src\\administrarAgenda\\img/uncheckedBox.png");
    
    
    /**
     * Creates new form ImprimirCitas111
     */
    public ImprimirCitas() {
        panelTransparente.setVisible(true);
        panelTransparente.setEnabled(false);
        initComponents();
        botonCheckBoxSabado.setIcon(uncheckedBox);
        botonCheckBoxDomingo.setIcon(uncheckedBox);
    }

    public void validaTipoEvento(){
       if(labelEvento.getText().equalsIgnoreCase("Check-In")){
           labelEvento.setText("Check-Out");
       } else if(labelEvento.getText().equalsIgnoreCase("Check-Out")){
           labelEvento.setText("Check-In");
       } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        labelDia = new javax.swing.JLabel();
        labelEvento = new javax.swing.JLabel();
        botonEvento = new javax.swing.JLabel();
        labelSabado = new javax.swing.JLabel();
        botonCheckBoxSabado = new javax.swing.JLabel();
        botonCheckBoxDomingo = new javax.swing.JLabel();
        labelDomingo = new javax.swing.JLabel();
        labelCopias = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        botonScrollUp = new javax.swing.JLabel();
        botonScrollDown = new javax.swing.JLabel();
        labelLineaHorizontal = new javax.swing.JLabel();
        botonListo = new javax.swing.JLabel();
        labelLineaVerticalChica = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelDia.setBackground(new java.awt.Color(153, 153, 153));
        labelDia.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelDia.setForeground(new java.awt.Color(255, 255, 255));
        labelDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDia.setText("Imprimir Citas");
        labelDia.setOpaque(true);

        labelEvento.setFont(new java.awt.Font("Roboto Cn", 0, 32)); // NOI18N
        labelEvento.setForeground(new java.awt.Color(153, 153, 153));
        labelEvento.setText("Check-In");
        labelEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEventoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEventoMouseExited(evt);
            }
        });
        labelEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelEventoMouseMoved(evt);
            }
        });

        botonEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/flecha.png"))); // NOI18N
        botonEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEventoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEventoMouseExited(evt);
            }
        });
        botonEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEventoMouseMoved(evt);
            }
        });

        labelSabado.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelSabado.setForeground(new java.awt.Color(51, 51, 51));
        labelSabado.setText("Sabado");
        labelSabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSabadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSabadoMouseExited(evt);
            }
        });
        labelSabado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelSabadoMouseMoved(evt);
            }
        });

        botonCheckBoxSabado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/uncheckedBox.png"))); // NOI18N
        botonCheckBoxSabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCheckBoxSabadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCheckBoxSabadoMouseExited(evt);
            }
        });
        botonCheckBoxSabado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCheckBoxSabadoMouseMoved(evt);
            }
        });

        botonCheckBoxDomingo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/uncheckedBox.png"))); // NOI18N
        botonCheckBoxDomingo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCheckBoxDomingoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCheckBoxDomingoMouseExited(evt);
            }
        });
        botonCheckBoxDomingo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCheckBoxDomingoMouseMoved(evt);
            }
        });

        labelDomingo.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelDomingo.setForeground(new java.awt.Color(51, 51, 51));
        labelDomingo.setText("Domingo");
        labelDomingo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDomingoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDomingoMouseExited(evt);
            }
        });
        labelDomingo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDomingoMouseMoved(evt);
            }
        });

        labelCopias.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelCopias.setForeground(new java.awt.Color(153, 153, 153));
        labelCopias.setText("Numero de Copias");

        labelNumero.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(51, 51, 51));
        labelNumero.setText("00");

        botonScrollUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/scrollerUp.png"))); // NOI18N
        botonScrollUp.setToolTipText("");
        botonScrollUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonScrollUpMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonScrollUpMouseExited(evt);
            }
        });
        botonScrollUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonScrollUpMouseMoved(evt);
            }
        });

        botonScrollDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/scrollerDown.png"))); // NOI18N
        botonScrollDown.setToolTipText("");
        botonScrollDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonScrollDownMouseExited(evt);
            }
        });
        botonScrollDown.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonScrollDownMouseMoved(evt);
            }
        });

        labelLineaHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/lineaHorizontal.png"))); // NOI18N

        botonListo.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonListo.setForeground(new java.awt.Color(0, 0, 0));
        botonListo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/botonAceptar.png"))); // NOI18N
        botonListo.setText("Listo");
        botonListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonListoMouseExited(evt);
            }
        });
        botonListo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonListoMouseMoved(evt);
            }
        });

        labelLineaVerticalChica.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        labelLineaVerticalChica.setForeground(new java.awt.Color(0, 0, 0));
        labelLineaVerticalChica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLineaVerticalChica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/lineaVertical.png"))); // NOI18N

        botonCancelar.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/botonCancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCancelarMouseExited(evt);
            }
        });
        botonCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCancelarMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLineaHorizontal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(labelCopias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEvento))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCheckBoxSabado)
                            .addComponent(botonCheckBoxDomingo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDomingo)
                            .addComponent(labelSabado))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(botonListo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLineaVerticalChica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelEvento)
                    .addComponent(botonEvento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCheckBoxSabado)
                    .addComponent(labelSabado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDomingo)
                    .addComponent(botonCheckBoxDomingo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCopias)
                        .addComponent(labelNumero))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(botonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(botonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLineaHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonListo)
                    .addComponent(labelLineaVerticalChica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar))
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(290, 269));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseClicked
        validaTipoEvento();
    }//GEN-LAST:event_labelEventoMouseClicked

    private void labelEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelEventoMouseExited

    private void labelEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelEventoMouseMoved

    private void botonEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseClicked
        validaTipoEvento();
    }//GEN-LAST:event_botonEventoMouseClicked

    private void botonEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonEventoMouseExited

    private void botonEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonEventoMouseMoved

    private void labelSabadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseClicked

    private void labelSabadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseExited

    private void labelSabadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseMoved

    private void botonCheckBoxSabadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxSabadoMouseClicked
        if(checkBoxSabado == 0){
            checkBoxSabado = 1;
            botonCheckBoxSabado.setIcon(checkBox);
        } else if(checkBoxSabado == 1){
            checkBoxSabado = 0;
            botonCheckBoxSabado.setIcon(uncheckedBox);
        }
    }//GEN-LAST:event_botonCheckBoxSabadoMouseClicked

    private void labelDomingoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseClicked

    private void labelDomingoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseExited

    private void labelDomingoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseMoved

    private void botonListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseClicked
        ConfirmacionImpresion confirmacionImpresion = new ConfirmacionImpresion();
        confirmacionImpresion.setVisible(true);
    }//GEN-LAST:event_botonListoMouseClicked

    private void botonListoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonListoMouseExited

    private void botonListoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonListoMouseMoved

    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseClicked
        panelTransparente.dispose();
        dispose();
    }//GEN-LAST:event_botonCancelarMouseClicked

    private void botonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonCancelarMouseExited

    private void botonCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonCancelarMouseMoved

    private void botonCheckBoxDomingoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxDomingoMouseClicked
        if(checkBoxDomingo == 0){
            checkBoxDomingo = 1;
            botonCheckBoxDomingo.setIcon(checkBox);
        } else if(checkBoxDomingo == 1){
            checkBoxDomingo = 0;
            botonCheckBoxDomingo.setIcon(uncheckedBox);
        }
    }//GEN-LAST:event_botonCheckBoxDomingoMouseClicked

    private void botonCheckBoxSabadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxSabadoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonCheckBoxSabadoMouseMoved

    private void botonCheckBoxSabadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxSabadoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonCheckBoxSabadoMouseExited

    private void botonCheckBoxDomingoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxDomingoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonCheckBoxDomingoMouseMoved

    private void botonCheckBoxDomingoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxDomingoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonCheckBoxDomingoMouseExited

    private void botonScrollUpMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonScrollUpMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonScrollUpMouseMoved

    private void botonScrollUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonScrollUpMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonScrollUpMouseExited

    private void botonScrollDownMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonScrollDownMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonScrollDownMouseMoved

    private void botonScrollDownMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonScrollDownMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonScrollDownMouseExited

    private void botonScrollUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonScrollUpMouseClicked
        String x = String.valueOf(labelNumero.getText());
        int i = Integer.parseInt(x);
        
        if(i<10){
            i++;
            switch(i){
                case 1: labelNumero.setText("01");
                    break;
                case 2: labelNumero.setText("02");
                    break;
                case 3: labelNumero.setText("03");
                    break;
                case 4: labelNumero.setText("04");
                    break;
                case 5: labelNumero.setText("05");
                    break;
                case 6: labelNumero.setText("06");
                    break;
                case 7: labelNumero.setText("07");
                    break;
                case 8: labelNumero.setText("08");
                    break;
                case 9: labelNumero.setText("09");
                    break;
                case 10: labelNumero.setText("10");
                    break;
            }
        } else if(i == 10){
            i = 0;
            labelNumero.setText("00");
        }
    }//GEN-LAST:event_botonScrollUpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirCitas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCancelar;
    private javax.swing.JLabel botonCheckBoxDomingo;
    private javax.swing.JLabel botonCheckBoxSabado;
    private javax.swing.JLabel botonEvento;
    private javax.swing.JLabel botonListo;
    private javax.swing.JLabel botonScrollDown;
    private javax.swing.JLabel botonScrollUp;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel labelCopias;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDomingo;
    private javax.swing.JLabel labelEvento;
    private javax.swing.JLabel labelLineaHorizontal;
    private javax.swing.JLabel labelLineaVerticalChica;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelSabado;
    // End of variables declaration//GEN-END:variables
}
