/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package administrarAgenda;

import java.awt.Cursor;
import javax.swing.ImageIcon;

/**
 *
 * @author JHumaran
 */
public class ImprimirCitas extends javax.swing.JFrame {
    PanelTransparente panelTransparente = new PanelTransparente();
    int checkBoxSabado = 0;
    int checkBoxDomingo = 0;
    ImageIcon checkBox = new ImageIcon("C:\\Users\\JHumaran\\Documents\\GitHub\\SAREI\\SAREI.Presentacion\\src\\administrarAgenda\\img/checkedBox.png"); 
    ImageIcon uncheckedBox = new ImageIcon("C:\\Users\\JHumaran\\Documents\\GitHub\\SAREI\\SAREI.Presentacion\\src\\administrarAgenda\\img/uncheckedBox.png");
    
    
    /**
     * Creates new form ImprimirCitas
     */
    public ImprimirCitas() {
        panelTransparente.setVisible(true);
        panelTransparente.setEnabled(false);
        initComponents();
        botonCheckBoxSabado.setIcon(uncheckedBox);
        botonCheckBoxDomingo.setIcon(uncheckedBox);
    }

    public void validaTipoEvento(){
       if(labelEvento.getText().equalsIgnoreCase("Check-In")){
           labelEvento.setText("Check-Out");
       } else if(labelEvento.getText().equalsIgnoreCase("Check-Out")){
           labelEvento.setText("Check-In");
       } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        labelDia = new javax.swing.JLabel();
        labelEvento = new javax.swing.JLabel();
        botonEvento = new javax.swing.JLabel();
        labelSabado = new javax.swing.JLabel();
        labelDomingo = new javax.swing.JLabel();
        labelCopias = new javax.swing.JLabel();
        labelNumero = new javax.swing.JLabel();
        botonScrollUp = new javax.swing.JLabel();
        botonScrollDown = new javax.swing.JLabel();
        botonListo = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JLabel();
        labelLineaVerticalChica = new javax.swing.JLabel();
        labelLineaHorizontal = new javax.swing.JLabel();
        botonCheckBoxSabado = new javax.swing.JLabel();
        botonCheckBoxDomingo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelDia.setBackground(new java.awt.Color(153, 153, 153));
        labelDia.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelDia.setForeground(new java.awt.Color(255, 255, 255));
        labelDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDia.setText("Imprimir Citas");
        labelDia.setOpaque(true);

        labelEvento.setFont(new java.awt.Font("Roboto Cn", 0, 32)); // NOI18N
        labelEvento.setForeground(new java.awt.Color(153, 153, 153));
        labelEvento.setText("Check-In");
        labelEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelEventoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelEventoMouseExited(evt);
            }
        });
        labelEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelEventoMouseMoved(evt);
            }
        });

        botonEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/flecha.png"))); // NOI18N
        botonEvento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonEventoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEventoMouseExited(evt);
            }
        });
        botonEvento.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonEventoMouseMoved(evt);
            }
        });

        labelSabado.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelSabado.setForeground(new java.awt.Color(51, 51, 51));
        labelSabado.setText("Sabado");
        labelSabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSabadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelSabadoMouseExited(evt);
            }
        });
        labelSabado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelSabadoMouseMoved(evt);
            }
        });

        labelDomingo.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelDomingo.setForeground(new java.awt.Color(51, 51, 51));
        labelDomingo.setText("Domingo");
        labelDomingo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDomingoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDomingoMouseExited(evt);
            }
        });
        labelDomingo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                labelDomingoMouseMoved(evt);
            }
        });

        labelCopias.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelCopias.setForeground(new java.awt.Color(153, 153, 153));
        labelCopias.setText("Numero de Copias");

        labelNumero.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelNumero.setForeground(new java.awt.Color(51, 51, 51));
        labelNumero.setText("00");

        botonScrollUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/scrollerUp.png"))); // NOI18N
        botonScrollUp.setToolTipText("");

        botonScrollDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/scrollerDown.png"))); // NOI18N
        botonScrollDown.setToolTipText("");

        botonListo.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonListo.setForeground(new java.awt.Color(0, 0, 0));
        botonListo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        botonListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/botonAceptar.png"))); // NOI18N
        botonListo.setText("Imprimir");
        botonListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonListoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonListoMouseExited(evt);
            }
        });
        botonListo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonListoMouseMoved(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        botonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/botonCancelar.png"))); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCancelarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCancelarMouseExited(evt);
            }
        });
        botonCancelar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonCancelarMouseMoved(evt);
            }
        });

        labelLineaVerticalChica.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        labelLineaVerticalChica.setForeground(new java.awt.Color(0, 0, 0));
        labelLineaVerticalChica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLineaVerticalChica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/lineaVertical.png"))); // NOI18N

        labelLineaHorizontal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/lineaHorizontal.png"))); // NOI18N

        botonCheckBoxSabado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/uncheckedBox.png"))); // NOI18N
        botonCheckBoxSabado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCheckBoxSabadoMouseClicked(evt);
            }
        });

        botonCheckBoxDomingo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/uncheckedBox.png"))); // NOI18N

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonCheckBoxSabado)
                            .addComponent(botonCheckBoxDomingo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDomingo)
                            .addComponent(labelSabado)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(labelEvento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEvento))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(labelCopias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLineaHorizontal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentPanelLayout.createSequentialGroup()
                        .addComponent(botonListo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLineaVerticalChica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addComponent(labelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEvento)
                            .addComponent(botonEvento))
                        .addGap(18, 18, 18)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelSabado)
                            .addComponent(botonCheckBoxSabado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDomingo)
                            .addComponent(botonCheckBoxDomingo))
                        .addGap(18, 18, 18)
                        .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCopias)
                            .addComponent(labelNumero)))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(botonScrollUp, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(botonScrollDown, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLineaHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonListo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentPanelLayout.createSequentialGroup()
                        .addComponent(labelLineaVerticalChica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseClicked
        validaTipoEvento();
    }//GEN-LAST:event_labelEventoMouseClicked

    private void labelEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_labelEventoMouseExited

    private void labelEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelEventoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelEventoMouseMoved

    private void botonEventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseClicked
        validaTipoEvento();
    }//GEN-LAST:event_botonEventoMouseClicked

    private void botonEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonEventoMouseExited

    private void botonEventoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEventoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonEventoMouseMoved

    private void labelSabadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseClicked

    private void labelSabadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseExited

    private void labelSabadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSabadoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelSabadoMouseMoved

    private void labelDomingoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseClicked

    private void labelDomingoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseExited

    private void labelDomingoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDomingoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDomingoMouseMoved

    private void botonListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseClicked
        panelTransparente.dispose();
        dispose();
    }//GEN-LAST:event_botonListoMouseClicked

    private void botonListoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonListoMouseExited

    private void botonListoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonListoMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonListoMouseMoved

    private void botonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseClicked
        panelTransparente.dispose();
        dispose();
    }//GEN-LAST:event_botonCancelarMouseClicked

    private void botonCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonCancelarMouseExited

    private void botonCancelarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonCancelarMouseMoved

    private void botonCheckBoxSabadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCheckBoxSabadoMouseClicked
        if(checkBoxSabado == 0){
            checkBoxSabado = 1;
            botonCheckBoxSabado.setIcon(checkBox);
        } else if(checkBoxSabado == 1){
            checkBoxSabado = 0;
            botonCheckBoxSabado.setIcon(uncheckedBox);
        }
    }//GEN-LAST:event_botonCheckBoxSabadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirCitas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonCancelar;
    private javax.swing.JLabel botonCheckBoxDomingo;
    private javax.swing.JLabel botonCheckBoxSabado;
    private javax.swing.JLabel botonEvento;
    private javax.swing.JLabel botonListo;
    private javax.swing.JLabel botonScrollDown;
    private javax.swing.JLabel botonScrollUp;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel labelCopias;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDomingo;
    private javax.swing.JLabel labelEvento;
    private javax.swing.JLabel labelLineaHorizontal;
    private javax.swing.JLabel labelLineaVerticalChica;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JLabel labelSabado;
    // End of variables declaration//GEN-END:variables
}
