/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package administrarAgenda;

import java.awt.Cursor;

/**
 *
 * @author JHumaran
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        containerPanel3 = new javax.swing.JPanel();
        headerPanel3 = new javax.swing.JPanel();
        detailHeaderPanel3 = new javax.swing.JPanel();
        botonNuevaCita = new javax.swing.JLabel();
        botonImprimir = new javax.swing.JLabel();
        iconoCalendar = new javax.swing.JLabel();
        labelEvento = new javax.swing.JLabel();
        botonEvento = new javax.swing.JLabel();
        diaLabel = new javax.swing.JLabel();
        botonDia = new javax.swing.JLabel();
        contentPanel = new javax.swing.JPanel();
        checkInSabadoPanel = new javax.swing.JPanel();
        botonCheckInSabado_1_1 = new javax.swing.JButton();
        botonCheckInSabado_1_2 = new javax.swing.JButton();
        botonCheckInSabado_1_3 = new javax.swing.JButton();
        botonCheckInSabado_1_4 = new javax.swing.JButton();
        botonCheckInSabado_1_5 = new javax.swing.JButton();
        botonCheckInSabado_1_6 = new javax.swing.JButton();
        botonCheckInSabado_1_7 = new javax.swing.JButton();
        botonCheckInSabado_2_1 = new javax.swing.JButton();
        botonCheckInSabado_2_2 = new javax.swing.JButton();
        botonCheckInSabado_2_3 = new javax.swing.JButton();
        botonCheckInSabado_2_4 = new javax.swing.JButton();
        botonCheckInSabado_2_5 = new javax.swing.JButton();
        botonCheckInSabado_2_6 = new javax.swing.JButton();
        botonCheckInSabado_2_7 = new javax.swing.JButton();
        botonCheckInSabado_3_1 = new javax.swing.JButton();
        botonCheckInSabado_3_2 = new javax.swing.JButton();
        botonCheckInSabado_3_3 = new javax.swing.JButton();
        botonCheckInSabado_3_4 = new javax.swing.JButton();
        botonCheckInSabado_3_5 = new javax.swing.JButton();
        botonCheckInSabado_3_6 = new javax.swing.JButton();
        botonCheckInSabado_3_7 = new javax.swing.JButton();
        botonCheckInSabado_4_1 = new javax.swing.JButton();
        botonCheckInSabado_5_1 = new javax.swing.JButton();
        botonCheckInSabado_6_1 = new javax.swing.JButton();
        botonCheckInSabado_7_1 = new javax.swing.JButton();
        botonCheckInSabado_8_1 = new javax.swing.JButton();
        botonCheckInSabado_9_1 = new javax.swing.JButton();
        botonCheckInSabado_10_1 = new javax.swing.JButton();
        botonCheckInSabado_11_1 = new javax.swing.JButton();
        botonCheckInSabado_12_1 = new javax.swing.JButton();
        botonCheckInSabado_13_1 = new javax.swing.JButton();
        botonCheckInSabado_14_1 = new javax.swing.JButton();
        botonCheckInSabado_15_1 = new javax.swing.JButton();
        botonCheckInSabado_16_1 = new javax.swing.JButton();
        botonCheckInSabado_17_1 = new javax.swing.JButton();
        botonCheckInSabado_4_2 = new javax.swing.JButton();
        botonCheckInSabado_4_3 = new javax.swing.JButton();
        botonCheckInSabado_4_4 = new javax.swing.JButton();
        botonCheckInSabado_4_5 = new javax.swing.JButton();
        botonCheckInSabado_4_6 = new javax.swing.JButton();
        botonCheckInSabado_4_7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerPanel3.setBackground(new java.awt.Color(255, 255, 255));
        containerPanel3.setForeground(new java.awt.Color(255, 255, 255));

        headerPanel3.setBackground(new java.awt.Color(217, 217, 217));

        detailHeaderPanel3.setBackground(new java.awt.Color(191, 191, 191));

        javax.swing.GroupLayout detailHeaderPanel3Layout = new javax.swing.GroupLayout(detailHeaderPanel3);
        detailHeaderPanel3.setLayout(detailHeaderPanel3Layout);
        detailHeaderPanel3Layout.setHorizontalGroup(
            detailHeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        detailHeaderPanel3Layout.setVerticalGroup(
            detailHeaderPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        botonNuevaCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/nuevaCita.png"))); // NOI18N
        botonNuevaCita.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                botonNuevaCitaMouseWheelMoved(evt);
            }
        });
        botonNuevaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonNuevaCitaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonNuevaCitaMouseExited(evt);
            }
        });
        botonNuevaCita.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonNuevaCitaMouseMoved(evt);
            }
        });

        botonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/imprimirCitas.png"))); // NOI18N
        botonImprimir.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                botonImprimirMouseWheelMoved(evt);
            }
        });
        botonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonImprimirMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonImprimirMouseExited(evt);
            }
        });
        botonImprimir.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonImprimirMouseMoved(evt);
            }
        });

        iconoCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/Google Calendar Icon.png"))); // NOI18N
        iconoCalendar.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                iconoCalendarMouseWheelMoved(evt);
            }
        });
        iconoCalendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoCalendarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconoCalendarMouseExited(evt);
            }
        });
        iconoCalendar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                iconoCalendarMouseMoved(evt);
            }
        });

        labelEvento.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        labelEvento.setForeground(new java.awt.Color(51, 51, 51));
        labelEvento.setText("Check-In");

        botonEvento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/flecha.png"))); // NOI18N

        javax.swing.GroupLayout headerPanel3Layout = new javax.swing.GroupLayout(headerPanel3);
        headerPanel3.setLayout(headerPanel3Layout);
        headerPanel3Layout.setHorizontalGroup(
            headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(iconoCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEvento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botonNuevaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
            .addComponent(detailHeaderPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPanel3Layout.setVerticalGroup(
            headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanel3Layout.createSequentialGroup()
                .addGroup(headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconoCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonNuevaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonEvento)
                            .addComponent(labelEvento))
                        .addGap(18, 18, 18)))
                .addComponent(detailHeaderPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        diaLabel.setFont(new java.awt.Font("Roboto Cn", 0, 30)); // NOI18N
        diaLabel.setForeground(new java.awt.Color(51, 51, 51));
        diaLabel.setText("Domingo");

        botonDia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/administrarAgenda/img/flecha.png"))); // NOI18N

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setLayout(new java.awt.CardLayout());

        checkInSabadoPanel.setBackground(new java.awt.Color(255, 255, 255));
        checkInSabadoPanel.setLayout(new java.awt.GridBagLayout());

        botonCheckInSabado_1_1.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_1.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_1.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_1.setText("Ala");
        botonCheckInSabado_1_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonCheckInSabado_1_1.setEnabled(false);
        botonCheckInSabado_1_1.setPreferredSize(new java.awt.Dimension(180, 60));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_1_1, gridBagConstraints);

        botonCheckInSabado_1_2.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_2.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_2.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_2.setText("Mujeres 1");
        botonCheckInSabado_1_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_2.setEnabled(false);
        botonCheckInSabado_1_2.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        checkInSabadoPanel.add(botonCheckInSabado_1_2, gridBagConstraints);

        botonCheckInSabado_1_3.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_3.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_3.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_3.setText("Hombres 1");
        botonCheckInSabado_1_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_3.setEnabled(false);
        botonCheckInSabado_1_3.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        checkInSabadoPanel.add(botonCheckInSabado_1_3, gridBagConstraints);

        botonCheckInSabado_1_4.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_4.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_4.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_4.setText("Mujeres 2");
        botonCheckInSabado_1_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_4.setEnabled(false);
        botonCheckInSabado_1_4.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        checkInSabadoPanel.add(botonCheckInSabado_1_4, gridBagConstraints);

        botonCheckInSabado_1_5.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_5.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_5.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_5.setText("Hombres 2");
        botonCheckInSabado_1_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_5.setEnabled(false);
        botonCheckInSabado_1_5.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        checkInSabadoPanel.add(botonCheckInSabado_1_5, gridBagConstraints);

        botonCheckInSabado_1_6.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_6.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_6.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_6.setText("Mujeres 3");
        botonCheckInSabado_1_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_6.setEnabled(false);
        botonCheckInSabado_1_6.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        checkInSabadoPanel.add(botonCheckInSabado_1_6, gridBagConstraints);

        botonCheckInSabado_1_7.setBackground(new java.awt.Color(242, 242, 242));
        botonCheckInSabado_1_7.setFont(new java.awt.Font("Roboto Cn", 0, 24)); // NOI18N
        botonCheckInSabado_1_7.setForeground(new java.awt.Color(127, 127, 127));
        botonCheckInSabado_1_7.setText("Hombres 3");
        botonCheckInSabado_1_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_1_7.setEnabled(false);
        botonCheckInSabado_1_7.setPreferredSize(new java.awt.Dimension(180, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        checkInSabadoPanel.add(botonCheckInSabado_1_7, gridBagConstraints);

        botonCheckInSabado_2_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_2_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_2_1.setText("9:00");
        botonCheckInSabado_2_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_1.setEnabled(false);
        botonCheckInSabado_2_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_1, gridBagConstraints);

        botonCheckInSabado_2_2.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_2.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_2, gridBagConstraints);

        botonCheckInSabado_2_3.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_3.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_3, gridBagConstraints);

        botonCheckInSabado_2_4.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_4.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_4, gridBagConstraints);

        botonCheckInSabado_2_5.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_5.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_5, gridBagConstraints);

        botonCheckInSabado_2_6.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_6.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_6, gridBagConstraints);

        botonCheckInSabado_2_7.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_2_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_2_7.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_2_7, gridBagConstraints);

        botonCheckInSabado_3_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_3_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_3_1.setText("9:30");
        botonCheckInSabado_3_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_1.setEnabled(false);
        botonCheckInSabado_3_1.setPreferredSize(new java.awt.Dimension(74, 34));
        botonCheckInSabado_3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCheckInSabado_3_1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_1, gridBagConstraints);

        botonCheckInSabado_3_2.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_2.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_2, gridBagConstraints);

        botonCheckInSabado_3_3.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_3.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_3, gridBagConstraints);

        botonCheckInSabado_3_4.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_4.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_4, gridBagConstraints);

        botonCheckInSabado_3_5.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_5.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_5, gridBagConstraints);

        botonCheckInSabado_3_6.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_6.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_6, gridBagConstraints);

        botonCheckInSabado_3_7.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_3_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_3_7.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_3_7, gridBagConstraints);

        botonCheckInSabado_4_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_4_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_4_1.setText("10:00");
        botonCheckInSabado_4_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_1.setEnabled(false);
        botonCheckInSabado_4_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_1, gridBagConstraints);

        botonCheckInSabado_5_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_5_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_5_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_5_1.setText("10:30");
        botonCheckInSabado_5_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_5_1.setEnabled(false);
        botonCheckInSabado_5_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_5_1, gridBagConstraints);

        botonCheckInSabado_6_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_6_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_6_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_6_1.setText("11:00");
        botonCheckInSabado_6_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_6_1.setEnabled(false);
        botonCheckInSabado_6_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_6_1, gridBagConstraints);

        botonCheckInSabado_7_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_7_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_7_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_7_1.setText("11:30");
        botonCheckInSabado_7_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_7_1.setEnabled(false);
        botonCheckInSabado_7_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_7_1, gridBagConstraints);

        botonCheckInSabado_8_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_8_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_8_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_8_1.setText("12:00");
        botonCheckInSabado_8_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_8_1.setEnabled(false);
        botonCheckInSabado_8_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_8_1, gridBagConstraints);

        botonCheckInSabado_9_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_9_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_9_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_9_1.setText("12:30");
        botonCheckInSabado_9_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_9_1.setEnabled(false);
        botonCheckInSabado_9_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_9_1, gridBagConstraints);

        botonCheckInSabado_10_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_10_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_10_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_10_1.setText("13:00");
        botonCheckInSabado_10_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_10_1.setEnabled(false);
        botonCheckInSabado_10_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_10_1, gridBagConstraints);

        botonCheckInSabado_11_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_11_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_11_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_11_1.setText("13:30");
        botonCheckInSabado_11_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_11_1.setEnabled(false);
        botonCheckInSabado_11_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_11_1, gridBagConstraints);

        botonCheckInSabado_12_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_12_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_12_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_12_1.setText("14:00");
        botonCheckInSabado_12_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_12_1.setEnabled(false);
        botonCheckInSabado_12_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_12_1, gridBagConstraints);

        botonCheckInSabado_13_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_13_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_13_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_13_1.setText("14:30");
        botonCheckInSabado_13_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_13_1.setEnabled(false);
        botonCheckInSabado_13_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_13_1, gridBagConstraints);

        botonCheckInSabado_14_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_14_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_14_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_14_1.setText("15:00");
        botonCheckInSabado_14_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_14_1.setEnabled(false);
        botonCheckInSabado_14_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 13;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_14_1, gridBagConstraints);

        botonCheckInSabado_15_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_15_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_15_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_15_1.setText("15:30");
        botonCheckInSabado_15_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_15_1.setEnabled(false);
        botonCheckInSabado_15_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_15_1, gridBagConstraints);

        botonCheckInSabado_16_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_16_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_16_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_16_1.setText("16:00");
        botonCheckInSabado_16_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_16_1.setEnabled(false);
        botonCheckInSabado_16_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_16_1, gridBagConstraints);

        botonCheckInSabado_17_1.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_17_1.setFont(new java.awt.Font("Roboto Cn", 0, 18)); // NOI18N
        botonCheckInSabado_17_1.setForeground(new java.awt.Color(166, 166, 166));
        botonCheckInSabado_17_1.setText("16:30");
        botonCheckInSabado_17_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_17_1.setEnabled(false);
        botonCheckInSabado_17_1.setPreferredSize(new java.awt.Dimension(74, 34));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_17_1, gridBagConstraints);

        botonCheckInSabado_4_2.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_2.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_2, gridBagConstraints);

        botonCheckInSabado_4_3.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_3.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_3, gridBagConstraints);

        botonCheckInSabado_4_4.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_4.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_4, gridBagConstraints);

        botonCheckInSabado_4_5.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_5.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_5, gridBagConstraints);

        botonCheckInSabado_4_6.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_6.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_6, gridBagConstraints);

        botonCheckInSabado_4_7.setBackground(new java.awt.Color(255, 255, 255));
        botonCheckInSabado_4_7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 191, 191)));
        botonCheckInSabado_4_7.setPreferredSize(new java.awt.Dimension(72, 67));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        checkInSabadoPanel.add(botonCheckInSabado_4_7, gridBagConstraints);

        contentPanel.add(checkInSabadoPanel, "card2");

        javax.swing.GroupLayout containerPanel3Layout = new javax.swing.GroupLayout(containerPanel3);
        containerPanel3.setLayout(containerPanel3Layout);
        containerPanel3Layout.setHorizontalGroup(
            containerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(diaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerPanel3Layout.setVerticalGroup(
            containerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanel3Layout.createSequentialGroup()
                .addComponent(headerPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(containerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diaLabel)
                    .addComponent(botonDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevaCitaMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_botonNuevaCitaMouseWheelMoved

    }//GEN-LAST:event_botonNuevaCitaMouseWheelMoved

    private void botonNuevaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevaCitaMouseClicked
        
    }//GEN-LAST:event_botonNuevaCitaMouseClicked

    private void botonNuevaCitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevaCitaMouseExited
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_botonNuevaCitaMouseExited

    private void botonNuevaCitaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevaCitaMouseMoved
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_botonNuevaCitaMouseMoved

    private void botonImprimirMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_botonImprimirMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirMouseWheelMoved

    private void botonImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirMouseClicked

    private void botonImprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirMouseExited

    private void botonImprimirMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonImprimirMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonImprimirMouseMoved

    private void iconoCalendarMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_iconoCalendarMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCalendarMouseWheelMoved

    private void iconoCalendarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCalendarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCalendarMouseClicked

    private void iconoCalendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCalendarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCalendarMouseExited

    private void iconoCalendarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoCalendarMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_iconoCalendarMouseMoved

    private void botonCheckInSabado_3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCheckInSabado_3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCheckInSabado_3_1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCheckInSabado_10_1;
    private javax.swing.JButton botonCheckInSabado_11_1;
    private javax.swing.JButton botonCheckInSabado_12_1;
    private javax.swing.JButton botonCheckInSabado_13_1;
    private javax.swing.JButton botonCheckInSabado_14_1;
    private javax.swing.JButton botonCheckInSabado_15_1;
    private javax.swing.JButton botonCheckInSabado_16_1;
    private javax.swing.JButton botonCheckInSabado_17_1;
    private javax.swing.JButton botonCheckInSabado_1_1;
    private javax.swing.JButton botonCheckInSabado_1_2;
    private javax.swing.JButton botonCheckInSabado_1_3;
    private javax.swing.JButton botonCheckInSabado_1_4;
    private javax.swing.JButton botonCheckInSabado_1_5;
    private javax.swing.JButton botonCheckInSabado_1_6;
    private javax.swing.JButton botonCheckInSabado_1_7;
    private javax.swing.JButton botonCheckInSabado_2_1;
    private javax.swing.JButton botonCheckInSabado_2_2;
    private javax.swing.JButton botonCheckInSabado_2_3;
    private javax.swing.JButton botonCheckInSabado_2_4;
    private javax.swing.JButton botonCheckInSabado_2_5;
    private javax.swing.JButton botonCheckInSabado_2_6;
    private javax.swing.JButton botonCheckInSabado_2_7;
    private javax.swing.JButton botonCheckInSabado_3_1;
    private javax.swing.JButton botonCheckInSabado_3_2;
    private javax.swing.JButton botonCheckInSabado_3_3;
    private javax.swing.JButton botonCheckInSabado_3_4;
    private javax.swing.JButton botonCheckInSabado_3_5;
    private javax.swing.JButton botonCheckInSabado_3_6;
    private javax.swing.JButton botonCheckInSabado_3_7;
    private javax.swing.JButton botonCheckInSabado_4_1;
    private javax.swing.JButton botonCheckInSabado_4_2;
    private javax.swing.JButton botonCheckInSabado_4_3;
    private javax.swing.JButton botonCheckInSabado_4_4;
    private javax.swing.JButton botonCheckInSabado_4_5;
    private javax.swing.JButton botonCheckInSabado_4_6;
    private javax.swing.JButton botonCheckInSabado_4_7;
    private javax.swing.JButton botonCheckInSabado_5_1;
    private javax.swing.JButton botonCheckInSabado_6_1;
    private javax.swing.JButton botonCheckInSabado_7_1;
    private javax.swing.JButton botonCheckInSabado_8_1;
    private javax.swing.JButton botonCheckInSabado_9_1;
    private javax.swing.JLabel botonDia;
    private javax.swing.JLabel botonEvento;
    private javax.swing.JLabel botonImprimir;
    private javax.swing.JLabel botonNuevaCita;
    private javax.swing.JPanel checkInSabadoPanel;
    private javax.swing.JPanel containerPanel3;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel detailHeaderPanel3;
    private javax.swing.JLabel diaLabel;
    private javax.swing.JPanel headerPanel3;
    private javax.swing.JLabel iconoCalendar;
    private javax.swing.JLabel labelEvento;
    // End of variables declaration//GEN-END:variables
}
